repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: \.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [--fix]
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
      - id: isort
        files: \.py$
