name: Check Frontend

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**"
    pull_request:
        branches:
            - main
        paths:
            - "frontend/**"

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
                - name: Checkout
                  uses: actions/checkout@v3
                - name: Install dependencies
                  run: npm install
                  working-directory: ./frontend
                - name: Build (include check with biome)
                  run: npm run build
                  working-directory: ./frontend