name: Check Backend

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
    pull_request:
        branches:
            - main
        paths:
            - "backend/**"
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: pip install -r requirements.txt
              working-directory: ./backend
            - name: Run pre-commit
              run: pre-commit run --all-files
              working-directory: ./backend